ignore:
  - "test**"
  - "src/application**"
  - "**test**"
  - "**application**"
  - "**/application**"
  - "**/test**"
  - "**external**"

coverage:
  precision: 2
  round: down
  range: "90...100"
