image: registry.gitlab.com/jlack/rdl:ci-docker-melodic

variables:
  WS_NAME: "twist_ws"

before_script:
  - apt-get update -qq -y
  - apt-get upgrade -y
  - rosdep update

after_script:
  - bash <(curl -s https://codecov.io/bash) -t "7993cded-c9de-4336-b792-7c1abbbf6f34"

stages:
  - test

build_and_test:
  stage: test
  retry: 1
  script:
    - echo $CI_PROJECT_NAME
    - mkdir -p $WS_NAME/src && cd $WS_NAME/src
    - git clone -b ${CI_COMMIT_REF_NAME} ${CI_REPOSITORY_URL}
    - cd .. && rosdep install --from-paths src -i -y --as-root apt:false
    - catkin config --init --mkdirs --install --extend /opt/ros/$ROS_DISTRO
    - catkin build
    - catkin run_tests
    - catkin_test_results build/
  artifacts:
    paths:
    - $WS_NAME/
    expire_in: 1 day
