# This TOML document contains the TWIST configurations.

title = "TWIST configurations"

# x, y, z, w
[locations]
  BedRoomKids = [ -6.25, 3.16, -0.68, 0.72]
  BedRoomSuite = [ -6.25, -0.72, -0.70, 0.72]
  DinningRoom = [ -2.50, 2.44, 0.73, 0.68]
  Hall = [ 1.03, 0.46, -0.70, 0.71]
  Kitchen = [ 4.87, 2.42, 0.70, 0.71]
  LivingRoom = [ -0.84, 3.10, 0.75, 0.66]
  WC = [ 0.98, 2.87, -0.73, 0.67]
  WCSuite = [ 5.92, -2.21, -0.72, 0.69]
